apiVersion: configsync.gke.io/v1alpha1
kind: RepoSync
metadata:
  # There can be at most one RepoSync object per namespace.
  # To enforce this restriction, the object name must be repo-sync. 
  name: repo-sync
  namespace: stockholm
  annotations: 
    configsync.gke.io/cluster-name-selector: admin
spec:
  # Since this is for a namespace repository, the format should be unstructured
  sourceFormat: unstructured
  git:
    # If you fork this repo, change the url to point to your fork
    repo: https://github.com/600lyy/Build-KRM-Platform.git
    # If you move the configs to a different branch, update the branch here
    branch: main
    dir: gcp-resources/stockholm
    auth: token
    # Refer to a Secret you create to hold the private key, cookiefile, or token.
    secretRef:
      name: git-creds